version: "3.8"

services:
  caddy:
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    network_mode: host

volumes:
  caddy-data:
  caddy-config:
