version: "3.8"

services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    build: .
    ports:
      - "80:80"
      - "443:443"

  certbot_trello:
    image: certbot/certbot
    depends_on:
      - application
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --email alexbidenko1998@gmail.com --agree-tos --no-eff-email --staging -d trello.admire.social -d www.trello.admire.social
    networks:
      - app-network
