version: "3.8"

services:
  caddy:
    restart: unless-stopped
    container_name: caddy
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
  caddy-config:

networks:
  default:
    external:
      name: server
