name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 400 ~/.ssh/id_rsa

      - name: Deploy 🚀
        run: |
          docker network create --driver bridge server || true
          docker-compose up -d --build --remove-orphans
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
